version: '3.9'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:${ADMINER_PORT}"
    command:
      - 'php'
      - '-S'
      - '[::]:${ADMINER_PORT}'
      - '-t'
      - '/var/www/html'
    depends_on:
      - db

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    depends_on:
      - db
    command: bash -c "alembic upgrade head && cd source && uvicorn main:app --host ${HOST} --port ${API_PORT}"